---

- name: Download file
  get_url: url=https://getcomposer.org/download/{{ drupal_composer_version }}/composer.phar mode="u=rwx,g=rx,o=rx" validate_certs=false
  args:
    headers: "User-Agent:Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
    dest: /tmp/composer-{{ drupal_composer_version }}.phar

- name: Create sha256sum file
  shell: "echo \"{{ drupal_composer_sha256 }}  composer-{{ drupal_composer_version }}.phar\" > composer-{{ drupal_composer_version }}.phar.sha256"
  args:
    chdir: /tmp

- name: Perform sha256sum
  shell: sha256sum composer-{{ drupal_composer_version }}.phar.sha256 -c
  args:
    chdir: /tmp

- name: Copy composer to /usr/local/bin
  shell: mv /tmp/composer-{{ drupal_composer_version }}.phar /usr/local/bin/composer

- name: Self-update composer
  shell: /usr/local/bin/composer self-update

- include: composer_vendor.yml
  with_items: "{{ drupal_drush_users }}"
