---

# Drush
# https://github.com/drush-ops/drush
# https://drushcommands.com/

- name: Download file
  get_url: url="https://github.com/drush-ops/drush/releases/download/{{ drupal_drush_version }}/drush.phar" mode="u=rwx,g=rx,o=rx" validate_certs=true
  args:
      dest: /tmp/drush-{{ drupal_drush_version }}.phar

- name: Create sha256sum file
  shell: "echo \"{{ drupal_drush_sha256 }}  drush-{{ drupal_drush_version }}.phar\" > drush-{{ drupal_drush_version }}.phar.sha256"
  args:
    chdir: /tmp

- name: Perform sha256sum
  shell: sha256sum drush-{{ drupal_drush_version }}.phar.sha256 -c
  args:
    chdir: /tmp

- name: Move
  shell: mv /tmp/drush-{{ drupal_drush_version }}.phar /usr/local/bin/drush
