---
# tasks file for ansible-drupal

#- name: Include Github tasks
#  include: github.yml

- name: Create Drupal Drush user
  user: name={{ item }} shell=/bin/bash groups={{ drupal_nginx_group }} append=yes createhome=yes
  with_items: "{{ drupal_drush_users }}"

- name: Include Composer tasks
  include: composer.yml

#- name: Include Drush tasks
#  include: drush.yml
#
#- name: restart Nginx
#  service: name=nginx state=restarted
