---
# tasks file for ansible-drupal

- user: name={{ drupal_drush_user }} shell=/bin/bash groups={{ drupal_nginx_group }} append=yes createhome=yes

# Install via Drush
# https://github.com/drush-ops/drush

# Install composer.
- include: composer.yml

# Install drush
- include: drush.yml

# http://echo.co/blog/more-drop-bucket-drupal-8-nginx-and-microcaching
# sudo drush dl drupal-8 --destination=/var/www --drupal-project-rename=drupal-demo
# sudo cd drupal-demo
# sudo composer update
# sudo drush site-install --db-url=mysql://root:i_am_root@127.0.0.1/drupaldemo --account-mail=orlissenberg@gmail.com --account-name=admin --account-pass=sure

- name: Set the correct access rights on the drupal site paths
  shell: chown {{ drupal_drush_user }}:{{ drupal_nginx_group }} -R {{ item.site_path }}
  with_items: drupal_sites

- name: Create nginx configuration for each site
  template: src=drupal.conf.j2 dest=/etc/nginx/sites-available/{{ item.site_name }}.conf
  with_items: drupal_sites

- name: Enable the sites
  file: src=/etc/nginx/sites-available/{{ item.site_name }}.conf dest=/etc/nginx/sites-enabled/{{ item.site_name }}.conf
  with_items: drupal_sites
  args:
    owner: root
    group: root
    state: link

- service: name=nginx state=restarted
