---

- name: Add user to the group
  user:
    name: "{{ item.site_owner }}"
    groups: "{{ item.site_group }}"
    append: yes
    state: present

# http://echo.co/blog/more-drop-bucket-drupal-8-nginx-and-microcaching
- name: Download Drupal 8 source with Drush
  shell: source ~/.bashrc && drush dl drupal-8 --destination=/var/www --drupal-project-rename={{ item.site_name }}
  args:
    executable: /bin/bash

- name: Set the correct access rights on the drupal site paths
  shell: chown {{ item.site_owner }}:{{ item.site_group }} -R {{ item.site_path }}

# --prefer-source or --prefer-dist (zipped)
# In either case, the API is not used.
- name: Download vendor packages
  shell: source ~/.bashrc && composer install --prefer-source
  become_user: "{{ item.site_owner }}"
  args:
    chdir: "{{ item.site_path }}"
    executable: /bin/bash

# http://docs.ansible.com/ansible/mysql_user_module.html
- name: Create MySQL user
  mysql_user:
    name: "{{ item.mysql_user_name }}"
    password: "{{ item.mysql_user_password }}"
    priv: '*.*:ALL'
    host: 127.0.0.1
    state: present

# https://drushcommands.com/
# GD module for PHP required
- name: Create MySQL Database
  shell: source ~/.bashrc && drush site-install --db-url=mysql://{{ item.mysql_user_name }}:{{ item.mysql_user_password }}@127.0.0.1/{{ item.mysql_database_name }} --account-mail={{ item.site_account_mail }} --account-name={{ item.site_account_name }} --account-pass={{ item.site_account_pass }} -y
  args:
    chdir: "{{ item.site_path }}"
    executable: /bin/bash

- name: Set the correct access rights on the drupal site paths
  shell: chown {{ item.site_owner }}:{{ item.site_group }} -R {{ item.site_path }}

- name: Create nginx configuration for each site
  template: src="php{{ drupal_php_version }}-drupal.conf.j2" dest="/etc/nginx/sites-available/{{ item.site_name }}.conf"

- name: Enable the sites
  file: src="/etc/nginx/sites-available/{{ item.site_name }}.conf" dest="/etc/nginx/sites-enabled/{{ item.site_name }}.conf"
  args:
    owner: root
    group: root
    state: link
